### ISSUE TITLE
Enable option to shorten waiting time after won/failed battle

### ISSUE THREAD

**Issue by msjasinski** [billyaraujo/bombermaaan#12]
The player must wait a long time after winning or losing a battle or a whole game, which is tedious. I have in mind screens with "Scoreboard" and "Victory" captions. One should be able to press space/enter or any key to continue.

Otherwise, great game. I think the new work should be merged with the official website. In the long term, adding campaign mode would be wonderful.

**Comment by billyaraujo** [comment]
Sure. Feel free to make your own fork, where you can change screens and other resources. Then you can commit back changes. Improvements are welcome. 

About campain mode also agree however building "boss" levels would need some new logic.

**Comment by billyaraujo** [comment]
Fixed with commit: 12f0481fe99201de8758ccafb01ad1a145c44165

**Comment by msjasinski** [comment]
I'm not much of a developer so it might be hard for me to fix things myself...
Thanks for helping out!
